pluginManagement {
    repositories {
        maven {
            name = "Fabric"
            url = "https://maven.fabricmc.net/"
        }
        mavenCentral()
        gradlePluginPortal()
    }
}

rootProject.name = "LinearReader-workspace"

include(":targets")
project(":targets").projectDir = file("modules/targets")

include(":targets:fabric_1_21_11")
project(":targets:fabric_1_21_11").projectDir = file("modules/targets/fabric_1_21_11")

include(":core")
project(":core").projectDir = file("modules/core")

include(":core-testkit")
project(":core-testkit").projectDir = file("modules/core-testkit")

include(":minecraft-api")
project(":minecraft-api").projectDir = file("modules/minecraft-api")
